variables:
  docker_image: pydb
  docker_container: pydb

stages:
  - build

build-package:
  tags:
    - shell
  stage: build
  allow_failure: false
  script:
    - docker build -t $docker_image .
    - docker run --network host --name $docker_container $docker_image
  after_script:
    - docker cp $docker_container:/app/dist/ /var/tmp/$docker_container
    - docker rm $docker_container
  artifacts:
    expire_in: 1 week
    paths:
      - /var/tmp/$docker_container/dist
