variables:
  docker_image: pydb
  docker_container: pydb

stages:
  - build

build-package:
  tags:
    - shell
  stage: build
  allow_failure: false
  script:
    - docker build -t $docker_image .
    - docker run --network host --name $docker_container $docker_image
  after_script:
    - docker cp $docker_container:/app/dist/ $CI_PROJECT_DIR
    - docker rm $docker_container
    - ls $CI_PROJECT_DIR
#  artifacts:
#    expire_in: 1 week
#    paths:
#      - dist/
