name: Build and Publish Package

on:
  push:
    branches: [ "master" ]
  release:
    types: [published]

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean previous builds
        run: rm -rf dist/

      # Установка Python и зависимостей
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      # Сборка пакета
      - name: Build package
        run: python -m build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

      # Публикация пакета в TestPyPI
      - name: Publish to TestPyPI (on push)
        if: github.event_name == 'push'
        run: twine upload --repository testpypi dist/* --skip-existing
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}

      # Публикация пакета в PyPI
      - name: Publish to PyPI (on release)
        if: github.event_name == 'release'
        run: twine upload dist/* --skip-existing
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
